### ISSUE TITLE
Embedded new version checker/autoupdater

### ISSUE THREAD

**Issue by arietto** [Basile-z/dexed#356]
Have you considered http://wiki.freepascal.org/LazAutoUpdater instead of curl usage?
This message "No suitable tool can be used to determine the latest version.Install at least CURL as a command line tool, visible in the PATH.Newest OpenSSL versions (>= 1.1) are currently not supported" looks too complicated. I suppose that Object Pascal community has out-of-the-box solution for such common task in 2018 year.

**Comment by BBasile** [comment]
No , i haven't considered it so far but this project is widely open to pull requests (meaning do it yourself if you can) The message you see is due to a slow release cycle of FPC (sometimes 2 years between two releases). I'm waiting for FPC http client to support most recent SSL versions but if someone can propose something better i would take.

**Comment by BBasile** [comment]
I've tried LazAutoUpdate http client and it has the same issues as the one from the standard library. Using this component would not help. Sadly, in 2018, we cannot do simple https requests with the FCL.

**Comment by Basile-z** [comment]
I close because just fixed the fundamental problem that caused the failure.
I still need to find libcurl.dll for win64 tho.
