### ISSUE TITLE
Limit memory used by the debugger

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#436]
There should be an option to limit memory used by the debugged program.

My program recently has hanged the computer by overflowing its memory. I want to limit it to 400MB during debugging.

**Comment by Basile-z** [comment]
if GDB has no option for this i cannot do anything.

**Comment by Basile-z** [comment]
GDB doesn't allow that. I've read carefully the manual again, asked on #gdb IRC channel, etc.
Since most of your issues are related to the GDB commander widget, you have to understand that's it's only a GUI that communicates with a daemonized soft (so gdb) via a shitty serialization format (aka GDB/MI) that everybody hates. I don't know where the money of the FSF goes BTW (caugh caugh).
They could have switched to JSON or XML since years but apparently there's a problem of deafness...

I know that GDB commander needs a big update.

**Comment by vporton** [comment]
Hm, `setrlimit()` can limit memory for _each_ (not for _both_) GDB and every process it spans. Not a perfect solution, but should be considered.

Notwithstanding the above, I found  some acceptable solution:

```
set environment LD_PRELOAD ./yourso.so
```

./yourso.so should call `setrlimit()` to limit the amount of virtual memory. I may probably spend some time on this yourso.so. Sorry, but not right now.
